---
apiVersion: v1
kind: Service
metadata:
  name: stock
  labels:
    app: stock
spec:
  type: NodePort
  selector:
    app: stock
  ports:
  - protocol: TCP
    port: 8030
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: stock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
      - name: stock
        image: 'docker.io/shabushabu/javashop.stock:latest'
        ports:
        - containerPort: 8030
        env:
          - name: SPLUNK_OTEL_AGENT
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=stock,deployment.environment=dd-k8s-1-25-2
 
          - name: SPLUNK_METRICS_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):9943
          
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):4317
          
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):9080/v1/trace
           #livenessProbe:
           #httpGet:
           #path: /health
           # port: 8030
           #initialDelaySeconds: 30
           #timeoutSeconds: 1
