---
apiVersion: v1
kind: Service
metadata:
  name: shop
  labels:
    app: shop
spec:
  type: NodePort
  selector:
    app: shop
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: 'docker.io/shabushabu/javashop.shop:latest'
        ports:
        - containerPort: 8010
        env:
          - name: SPLUNK_OTEL_AGENT
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=shop,deployment.environment=dd-k8s-1-25-2
          
          - name: SPLUNK_METRICS_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):9943
          
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):4317
          
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):9080/v1/trace
                
                
        #livenessProbe:
        # httpGet:
        #path: /health
        #port: 8010
        #initialDelaySeconds: 30
        #timeoutSeconds: 1 

