---
apiVersion: v1
kind: Service
metadata:
  name: instruments
  labels:
    app: instruments
spec:
  type: NodePort
  selector:
    app: instruments
  ports:
  - protocol: TCP
    port: 8040
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: instruments
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: instruments
    spec:
      containers:
      - name: instruments
        image: 'docker.io/shabushabu/javashop.instruments:latest'
        ports:
        - containerPort: 8040
        env:
          - name: SPLUNK_OTEL_AGENT
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=instrumentsß,deployment.environment=dd-k8s-1-25-2
 
          - name: SPLUNK_METRICS_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):9943
          
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):4317
          
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):9080/v1/trace
           #livenessProbe:
           #httpGet:
           #path: /health
           # port: 8030
           #initialDelaySeconds: 30
           #timeoutSeconds: 1
