---
apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    app: products
spec:
  type: NodePort
  selector:
    app: products
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: products
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: 'docker.io/shabushabu/javashop.products:latest'
        ports:
        - containerPort: 8020
        env:
          - name: SPLUNK_OTEL_AGENT
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=products,deployment.environment=dd-k8s-1-25-2
          
          - name: SPLUNK_METRICS_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):9943
          
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):4317
          
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):9080/v1/trace

                # livenessProbe:
                #httpGet:
                #path: /healthcheck
                #port: 8025
                #initialDelaySeconds: 30
                #timeoutSeconds: 1
