DROP TABLE IF EXISTS instruments_for_sale_chicago;
CREATE TABLE IF NOT EXISTS instruments_for_sale_chicago(
   ID              VARCHAR(50) NOT NULL PRIMARY KEY
  ,Title           VARCHAR(140) NOT NULL
  ,Sub_title       VARCHAR(58) NOT NULL
  ,Price           VARCHAR(12) NOT NULL
  ,Instrument_Type VARCHAR(29) NOT NULL
  ,Condition       VARCHAR(4) NOT NULL
  ,Location        VARCHAR(33) NOT NULL
  ,Post_URL        VARCHAR(114) NOT NULL
  ,Seller_type     VARCHAR(14) NOT NULL
  ,published_date  VARCHAR(14) NOT NULL
);

INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('1','Yamaha (SY-77) Music Synthesizer for sale','Posted on 04 Oct 7:11 pm, Ja-Ela, Gampaha','Rs 39,000','Keyboard / Piano','Used','Ja-Ela,  Gampaha','https://ikman.lk/en/ad/yamaha-sy-77-music-synthesizer-for-sale-gampaha-2','Member','10/4/21 19:11');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('2','SRX-718 BASS BIN (PAIR) for sale','Posted on 10 Oct 7:54 pm, Kadawatha, Gampaha','Rs 77,500','Studio / Live Music Equipment','New','Kadawatha,  Gampaha','https://ikman.lk/en/ad/srx-718-bass-bin-pair-for-sale-gampaha-1','Member','10/10/21 19:54');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('3','Piano (Malcom Mendis Piano) for sale','Posted on 13 Oct 12:43 pm, Kandana, Gampaha','Rs 130,000','Keyboard / Piano','Used','Kandana,  Gampaha','https://ikman.lk/en/ad/piano-malcom-mendis-piano-for-sale-gampaha-1','Member','10/13/21 12:43');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('4','Yamaha Semi Acoustic Guitars for sale','Posted on 13 Oct 12:44 pm, Rajagiriya, Colombo','Rs 36,000','String Instrument / Amplifier','Used','Rajagiriya,  Colombo','https://ikman.lk/en/ad/yamaha-semi-acoustic-guitar-for-sale-colombo-2','Member','10/13/21 12:44');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('5','Yamaha Guitar for sale','Posted on 13 Oct 12:06 pm, Delgoda, Gampaha','Rs 35,000','String Instrument / Amplifier','Used','Delgoda,  Gampaha','https://ikman.lk/en/ad/yamaha-guitar-ex-for-sale-gampaha','Member','10/13/21 12:06');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('6','Violin for sale','Posted on 13 Oct 12:04 pm, Galgamuwa, Kurunegala','Rs 7,500','String Instrument / Amplifier','New','Galgamuwa,  Kurunegala','https://ikman.lk/en/ad/violin-for-sale-kurunegala-169','Member','10/13/21 12:04');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('7','Expnsoin Card Xp 30.50.60.80 for sale','Posted on 13 Oct 11:57 am, Eheliyagoda, Ratnapura','Rs 10,000','Keyboard / Piano','Used','Eheliyagoda,  Ratnapura','https://ikman.lk/en/ad/expnsoin-card-xp-30506080-for-sale-ratnapura','Member','10/13/21 11:57');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('8','semi acoustic box guitar for sale','Posted on 13 Oct 11:55 am, Pilimatalawa, Kandy','Rs 13,250','String Instrument / Amplifier','New','Pilimatalawa,  Kandy','https://ikman.lk/en/ad/semi-acoustic-box-guitar-for-sale-kandy-4','Member','10/13/21 11:55');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('9','32 keys Melodica full set for sale','Posted on 13 Oct 11:50 am, Pilimatalawa, Kandy','Rs 2,750','String Instrument / Amplifier','New','Pilimatalawa,  Kandy','https://ikman.lk/en/ad/32-keys-melodica-full-set-for-sale-kandy','Member','10/13/21 11:50');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('10','Guitar wall stand for sale','Posted on 13 Oct 11:49 am, Pilimatalawa, Kandy','Rs 999','String Instrument / Amplifier','New','Pilimatalawa,  Kandy','https://ikman.lk/en/ad/guitar-wall-stand-for-sale-kandy','Member','10/13/21 11:49');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('11','Fender 41" box guitar for sale','Posted on 13 Oct 11:46 am, Pilimatalawa, Kandy','Rs 14,900','String Instrument / Amplifier','New','Pilimatalawa,  Kandy','https://ikman.lk/en/ad/fender-41-box-guitar-for-sale-kandy','Member','10/13/21 11:46');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('12','Dilipsons Piano Center for sale','Posted on 13 Oct 11:31 am, Wattala, Gampaha','Rs 250,000','Keyboard / Piano','Used','Wattala,  Gampaha','https://ikman.lk/en/ad/dilipsons-piano-center-for-sale-gampaha','Member','10/13/21 11:31');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('13','Sarpina for sale','Posted on 13 Oct 11:31 am, Divulapitiya, Gampaha','Rs 46,999','Keyboard / Piano','Used','Divulapitiya,  Gampaha','https://ikman.lk/en/ad/sarpina-for-sale-gampaha-1','Member','10/13/21 11:31');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('14','Electric Guitar for sale','Posted on 13 Oct 11:30 am, Wadduwa, Kalutara','Rs 15,000','String Instrument / Amplifier','Used','Wadduwa,  Kalutara','https://ikman.lk/en/ad/electric-guitar-for-sale-kalutara-111','Member','10/13/21 11:30');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('15','38 " Brand new guitar- √†¬∂¬∏√†¬∑¬ô√†¬∂¬∏ ','Posted on 13 Oct 11:26 am, Pilimatalawa, Kandy','Rs 8,800','String Instrument / Amplifier','New','Pilimatalawa,  Kandy','https://ikman.lk/en/ad/38-brand-new-box-guitar-for-sale-kandy-5','Member','10/13/21 11:26');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('16','Crossover X Pro for sale','Posted on 13 Oct 11:19 am, Pallepola, Matale','Rs 9,000','Studio / Live Music Equipment','Used','Pallepola,  Matale','https://ikman.lk/en/ad/9000-for-sale-matale','Member','10/13/21 11:19');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('17','10" / 12" 14" cymbals plates for sale','Posted on 09 Oct 7:00 pm, Kegalle City, Kegalle','Rs 1,800','Percussion / drums','New','Kegalle City,  Kegalle','https://ikman.lk/en/ad/10-12-14-cymbals-plates-for-sale-kegalle','Member','10/9/21 19:00');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('18','Full Drum Set Junior 5 pieces Felcon Brand New (Thailand) for sale','Posted on 13 Oct 10:59 am, Athurugiriya, Colombo','Rs 38,000','Percussion / drums','New','Athurugiriya,  Colombo','https://ikman.lk/en/ad/full-drum-set-junior-5-pieces-felcon-brand-new-thailand-for-sale-colombo','Member','10/13/21 10:59');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('19','Duble Top for sale','Posted on 13 Oct 10:47 am, Pannala, Kurunegala','Rs 60,000','Studio / Live Music Equipment','Used','Pannala,  Kurunegala','https://ikman.lk/en/ad/duble-top-for-sale-kurunegala','Member','10/13/21 10:47');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('20','Yamaha PSR 433 Keyboard for sale','Posted on 13 Oct 10:18 am, Dehiwala, Colombo','Rs 55,000','Keyboard / Piano','Used','Dehiwala,  Colombo','https://ikman.lk/en/ad/yamaha-psr-433-keyboard-for-sale-colombo','Member','10/13/21 10:18');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('21','Boss Pw3 Wah Pedal for sale','Posted on 11 Oct 10:02 am, Colombo 5, Colombo','Rs 19,000','Studio / Live Music Equipment','Used','Colombo 5,  Colombo','https://ikman.lk/en/ad/boss-pw3-wah-pedal-for-sale-colombo','Member','10/11/21 10:02');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('22','Atlas Japanese Piano for sale','Posted on 04 Oct 4:02 pm, Kandana, Gampaha','Rs 165,000','Keyboard / Piano','Used','Kandana,  Gampaha','https://ikman.lk/en/ad/atlas-japanese-piano-for-sale-gampaha','Member','10/4/21 16:02');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('23','Maverick Semi - Acoustic Guitar for sale','Posted on 13 Oct 10:04 am, Kotte, Colombo','Rs 14,500','String Instrument / Amplifier','New','Kotte,  Colombo','https://ikman.lk/en/ad/maverick-semi-acoustic-guitar-for-sale-colombo-5','Member','10/13/21 10:04');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('24','EMG James Hetfield Signature Pickups for sale','Posted on 13 Oct 10:01 am, Elpitiya, Galle','Rs 55,000','String Instrument / Amplifier','New','Elpitiya,  Galle','https://ikman.lk/en/ad/emg-james-hetfield-signature-pickups-for-sale-galle','Member','10/13/21 10:01');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('25','Genuine Joyroom (MC-03) Microphone & Speaker Phone Mic Holder - Black for sale','Posted on 13 Oct 9:58 am, Maharagama, Colombo','Rs 4,799','Other Instrument','New','Maharagama,  Colombo','https://ikman.lk/en/ad/genuine-joyroom-mc-03-microphone-and-speaker-phone-mic-holder-black-for-sale-colombo-5','Member','10/13/21 9:58');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('26','Classical Guitars Olivetree New for sale','Posted on 31 Aug 4:16 am, Colombo 15, Colombo','Rs 8,950','String Instrument / Amplifier','New','Colombo 15,  Colombo','https://ikman.lk/en/ad/classical-guitars-olivetree-new-for-sale-colombo','Member','8/31/21 4:16');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('27','Classical Guitar for sale','Posted on 30 Sep 10:14 pm, Minuwangoda, Gampaha','Rs 7,900','Studio / Live Music Equipment','Used','Minuwangoda,  Gampaha','https://ikman.lk/en/ad/classical-guitar-for-sale-gampaha-282','Member','9/30/21 22:14');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('28','Melodica for sale','Posted on 22 Sep 1:18 pm, Pannipitiya, Colombo','Rs 3,500','Keyboard / Piano','New','Pannipitiya,  Colombo','https://ikman.lk/en/ad/melodica-for-sale-colombo-89','Member','9/22/21 13:18');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('29','Yamaha SL380 Les Paul Electric Guitar for sale','Posted on 12 Oct 2:00 pm, Maharagama, Colombo','Rs 78,000','String Instrument / Amplifier','Used','Maharagama,  Colombo','https://ikman.lk/en/ad/1978-yamaha-sl380-les-paul-electric-guitar-for-sale-colombo','Member','10/12/21 14:00');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('30','Yamaha PSRE373 Keyboard for sale','Posted on 13 Oct 9:45 am, Ragama, Gampaha','Rs 53,000','Keyboard / Piano','New','Ragama,  Gampaha','https://ikman.lk/en/ad/yamaha-psre373-keyboard-for-sale-gampaha','Member','10/13/21 9:45');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('31','Guitar for sale','Posted on 22 Sep 1:20 pm, Pannipitiya, Colombo','Rs 5,950','String Instrument / Amplifier','New','Pannipitiya,  Colombo','https://ikman.lk/en/ad/guitar-for-sale-colombo-2178','Member','9/22/21 13:20');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('32','Guitar Stand for sale','Posted on 07 Oct 3:29 pm, Pannipitiya, Colombo','Rs 1,800','String Instrument / Amplifier','New','Pannipitiya,  Colombo','https://ikman.lk/en/ad/guitar-stand-for-sale-colombo-24','Member','10/7/21 15:29');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('33','Yamaha Hs8 Studio Monitors for sale','Posted on 13 Oct 9:29 am, Moratuwa, Colombo','Rs 170,000','Studio / Live Music Equipment','New','Moratuwa,  Colombo','https://ikman.lk/en/ad/yamaha-hs8-studio-monitors-for-sale-colombo-3','Member','10/13/21 9:29');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('34','Kuda Drum Set for sale','Posted on 13 Oct 9:33 am, Gampaha City, Gampaha','Rs 5,000','Percussion / drums','Used','Gampaha City,  Gampaha','https://ikman.lk/en/ad/kuda-drumset-ekak-wikiniimata-for-sale-gampaha','Member','10/13/21 9:33');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('35','Ibanez Sr 300 Ipt Bass Guitar for sale','Posted on 13 Oct 9:22 am, Kottawa, Colombo','Rs 65,000','String Instrument / Amplifier','New','Kottawa,  Colombo','https://ikman.lk/en/ad/ibanez-sr-300-ipt-bass-guitar-for-sale-colombo-3','Member','10/13/21 9:22');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('36','Roland XP 80 keyboard for sale','Posted on 13 Oct 9:18 am, Wattala, Gampaha','Rs 130,000','Keyboard / Piano','Used','Wattala,  Gampaha','https://ikman.lk/en/ad/roland-xp-80-for-sale-gampaha-34','Member','10/13/21 9:18');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('37','Crossover X pro 12000 for sale','Posted on 13 Oct 8:46 am, Pallepola, Matale','Rs 9,000','String Instrument / Amplifier','Used','Pallepola,  Matale','https://ikman.lk/en/ad/12000-for-sale-matale','Member','10/13/21 8:46');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('38','NUMARK MIXTRACK 3-JAPAN for sale','Posted on 13 Oct 8:41 am, Piliyandala, Colombo','Rs 25,000','Studio / Live Music Equipment','Used','Piliyandala,  Colombo','https://ikman.lk/en/ad/numark-mixtrack-3-japan-for-sale-colombo','Member','10/13/21 8:41');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('39','Onkyo TX SR 706 for sale','Posted on 13 Oct 8:40 am, Minuwangoda, Gampaha','Rs 15,500','Studio / Live Music Equipment','Used','Minuwangoda,  Gampaha','https://ikman.lk/en/ad/onkyo-tx-sr-706-for-sale-gampaha','Member','10/13/21 8:40');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('40','Thama Drama Set for sale','Posted on 13 Oct 8:01 am, Ambalangoda, Galle','Rs 88,000','Percussion / drums','Used','Ambalangoda,  Galle','https://ikman.lk/en/ad/thama-drama-set-for-sale-galle','Member','10/13/21 8:01');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('41','Guitar for sale','Posted on 13 Oct 7:44 am, Colombo 8, Colombo','Rs 10,000','String Instrument / Amplifier','Used','Colombo 8,  Colombo','https://ikman.lk/en/ad/urgent-for-sale-colombo-585','Member','10/13/21 7:44');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('42','Yamaha Pacifica Lead Guitar for sale','Posted on 13 Oct 7:26 am, Panadura, Kalutara','Rs 80,000','String Instrument / Amplifier','Used','Panadura,  Kalutara','https://ikman.lk/en/ad/yamaha-pacifica-lead-guitar-for-sale-kalutara','Member','10/13/21 7:26');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('43','Yamaha SL380 Les Paul Electric Guitar for sale','Posted on 12 Oct 2:00 pm, Maharagama, Colombo','Rs 78,000','String Instrument / Amplifier','Used','Maharagama,  Colombo','https://ikman.lk/en/ad/1978-yamaha-sl380-les-paul-electric-guitar-for-sale-colombo','Member','10/12/21 14:00');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('44','Yamaha Pacifica PAC 012 for sale','Posted on 13 Oct 6:20 am, Panadura, Kalutara','Rs 80,000','String Instrument / Amplifier','Used','Panadura,  Kalutara','https://ikman.lk/en/ad/ikamanin-vikinimata-for-sale-kalutara','Member','10/13/21 6:20');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('45','Supreme Lark violin for sale','Posted on 13 Oct 5:17 am, Kurunegala City, Kurunegala','Rs 6,000','String Instrument / Amplifier','Used','Kurunegala City,  Kurunegala','https://ikman.lk/en/ad/supreme-lark-violin-for-sale-kurunegala','Member','10/13/21 5:17');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('46','YAMAHA PSR -EW400 keyboard for sale','Posted on 13 Oct 4:54 am, Dehiwala, Colombo','Rs 72,000','Keyboard / Piano','Used','Dehiwala,  Colombo','https://ikman.lk/en/ad/yamaha-psr-ew400-for-sale-colombo','Member','10/13/21 4:54');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('47','Bass Drum Microphone for sale','Posted on 13 Oct 4:22 am, Moratuwa, Colombo','Rs 12,500','Studio / Live Music Equipment','Used','Moratuwa,  Colombo','https://ikman.lk/en/ad/bass-drum-microphone-for-sale-colombo','Member','10/13/21 4:22');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('48','percussion instruments for sale','Posted on 13 Oct 4:12 am, Moratuwa, Colombo','Rs 20,000','Percussion / drums','Used','Moratuwa,  Colombo','https://ikman.lk/en/ad/percussion-instruments-for-sale-colombo','Member','10/13/21 4:12');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('49','Darbuka Drums for sale','Posted on 13 Oct 3:12 am, Kaduwela, Colombo','Rs 3,500','Percussion / drums','New','Kaduwela,  Colombo','https://ikman.lk/en/ad/darbuk-drums-for-sale-for-sale-colombo','Member','10/13/21 3:12');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('50','Double Top Speakers for sale','Posted on 13 Oct 8:52 am, Hettipola, Kurunegala','Rs 10,500','Studio / Live Music Equipment','Used','Hettipola,  Kurunegala','https://ikman.lk/en/ad/spiikr-for-sale-kurunegala-8','Member','10/13/21 8:52');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('51','Bongo for sale','Posted on 13 Oct 2:06 am, Dehiwala, Colombo','Rs 4,500','Percussion / drums','Used','Dehiwala,  Colombo','https://ikman.lk/en/ad/bongo-for-sale-colombo-70','Member','10/13/21 2:06');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('52','Tascam US122MKII USB Audio/Midi Interface for sale','Posted on 13 Oct 7:59 am, Warakapola, Kegalle','Rs 13,500','Studio / Live Music Equipment','Used','Warakapola,  Kegalle','https://ikman.lk/en/ad/tascam-us122mkii-usb-audio-midi-interface-for-sale-kegalle','Member','10/13/21 7:59');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('53','BOYA BY-PM500 USB Condenser Microphone for sale','Posted on 12 Oct 11:10 pm, Maharagama, Colombo','Rs 17,000','Studio / Live Music Equipment','Used','Maharagama,  Colombo','https://ikman.lk/en/ad/boya-by-pm500-usb-condenser-microphone-with-warranty-for-sale-colombo','Member','10/12/21 23:10');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('54','Midi Drum Kit for sale','Posted on 12 Oct 10:46 pm, Gampaha City, Gampaha','Rs 47,000','Percussion / drums','Used','Gampaha City,  Gampaha','https://ikman.lk/en/ad/midi-drum-kit-for-sale-gampaha','Member','10/12/21 22:46');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('55','Yamaha E403 Keyboard for sale','Posted on 12 Oct 11:04 pm, Wennappuwa, Puttalam','Rs 45,000','Keyboard / Piano','Used','Wennappuwa,  Puttalam','https://ikman.lk/en/ad/yamaha-e403-for-sale-puttalam','Member','10/12/21 23:04');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('56','Midi Cable Octapad for sale','Posted on 12 Oct 9:53 pm, Kurunegala City, Kurunegala','Rs 40,000','Percussion / drums','Used','Kurunegala City,  Kurunegala','https://ikman.lk/en/ad/midi-caple-octer-pad-for-sale-kurunegala','Member','10/12/21 21:53');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('57','Original JBL PBM100 Wired Dynamic Vocal Microphone Mic for PartyBox for sale','Posted on 12 Oct 9:22 pm, Maharagama, Colombo','Rs 12,500','Studio / Live Music Equipment','New','Maharagama,  Colombo','https://ikman.lk/en/ad/original-jbl-pbm100-wired-dynamic-vocal-microphone-mic-for-partybox-for-sale-colombo','Member','10/12/21 21:22');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('58','Clayderman Piano ( Peterson Center ) for sale','Posted on 05 Oct 6:53 pm, Kandana, Gampaha','Rs 165,000','Keyboard / Piano','Used','Kandana,  Gampaha','https://ikman.lk/en/ad/clayderman-piano-peterson-center-for-sale-gampaha-1','Member','10/5/21 18:53');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('59','ZOOM PLAYER 3000 guitar pedal for sale','Posted on 12 Oct 8:10 pm, Wadduwa, Kalutara','Rs 12,500','Studio / Live Music Equipment','Used','Wadduwa,  Kalutara','https://ikman.lk/en/ad/zoom-player-3000-guitar-pedal-for-sale-kalutara','Member','10/12/21 20:10');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('60','ROLAND DRUM RACE for sale','Posted on 12 Oct 7:48 pm, Wadduwa, Kalutara','Rs 32,500','Percussion / drums','Used','Wadduwa,  Kalutara','https://ikman.lk/en/ad/roland-drum-race-for-sale-kalutara','Member','10/12/21 19:48');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('61','Samson Airline 88 AG8 Guitar - UHF Wireless System for sale','Posted on 12 Oct 7:25 pm, Colombo 11, Colombo','Rs 49,200','Studio / Live Music Equipment','New','Colombo 11,  Colombo','https://ikman.lk/en/ad/samson-airline-88-ag8-guitar-uhf-wireless-system-for-sale-colombo-1','Member','10/12/21 19:25');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('62','SRX-718 BASS BIN (PAIR) for sale','Posted on 10 Oct 7:54 pm, Kadawatha, Gampaha','Rs 77,500','Studio / Live Music Equipment','New','Kadawatha,  Gampaha','https://ikman.lk/en/ad/srx-718-bass-bin-pair-for-sale-gampaha-1','Member','10/10/21 19:54');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('63','SRX-725 (IMPORTED) DOUBLE TOP (PAIR) for sale','Posted on 10 Oct 7:54 pm, Kadawatha, Gampaha','Rs 148,000','Studio / Live Music Equipment','New','Kadawatha,  Gampaha','https://ikman.lk/en/ad/srx-725-imported-double-top-pair-for-sale-gampaha-1','Member','10/10/21 19:54');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('64','Guitar for sale','Posted on 07 Oct 4:27 pm, Kegalle City, Kegalle','Rs 8,600','String Instrument / Amplifier','New','Kegalle City,  Kegalle','https://ikman.lk/en/ad/guitar-for-sale-kegalle-100','Member','10/7/21 16:27');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('65','Original hardcases for keyboards.49.5"x16"x6". for sale','Posted on 12 Oct 6:58 pm, Wadduwa, Kalutara','Rs 22,000','Other Instrument','Used','Wadduwa,  Kalutara','https://ikman.lk/en/ad/original-hardcases-for-keyboards495x16x6-for-sale-kalutara','Member','10/12/21 18:58');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('66','KORG TONEWORK AX100G for sale','Posted on 12 Oct 6:48 pm, Wadduwa, Kalutara','Rs 13,500','Studio / Live Music Equipment','Used','Wadduwa,  Kalutara','https://ikman.lk/en/ad/korg-tonework-ax100g-for-sale-kalutara','Member','10/12/21 18:48');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('67','FORMESTAR Lead guitar. No strings. for sale','Posted on 12 Oct 6:35 pm, Wadduwa, Kalutara','Rs 8,500','String Instrument / Amplifier','Used','Wadduwa,  Kalutara','https://ikman.lk/en/ad/formestar-lead-guitar-no-strings-for-sale-kalutara','Member','10/12/21 18:35');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('68','Saxaphone - Soprano for sale','Posted on 13 Oct 12:32 pm, Dehiwala, Colombo','Rs 70,000','Woodwind / brass','Used','Dehiwala,  Colombo','https://ikman.lk/en/ad/saxaphone-soprano-for-sale-colombo','Member','10/13/21 12:32');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('69','Laid Back Free amp 4 strings bass guitar for sale','Posted on 12 Oct 6:25 pm, Wadduwa, Kalutara','Rs 37,500','String Instrument / Amplifier','Used','Wadduwa,  Kalutara','https://ikman.lk/en/ad/laid-back-free-amp-4-strings-bass-guitar-for-sale-kalutara-1','Member','10/12/21 18:25');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('70','AULOS ALTO 309A flute for sale','Posted on 12 Oct 6:06 pm, Wadduwa, Kalutara','Rs 4,000','Other Instrument','Used','Wadduwa,  Kalutara','https://ikman.lk/en/ad/aulos-alto-309a-flute-for-sale-kalutara','Member','10/12/21 18:06');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('71','Yamaha Clavinova CVP-206 Digital Piano for sale','Posted on 07 Oct 5:45 pm, Ja-Ela, Gampaha','Rs 190,000','Keyboard / Piano','Used','Ja-Ela,  Gampaha','https://ikman.lk/en/ad/yamaha-clavinova-cvp-206-digital-piano-for-sale-gampaha','Member','10/7/21 17:45');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('72','Piano (Nevil Mendis Piano) for sale','Posted on 02 Oct 8:50 am, Ragama, Gampaha','Rs 135,000','Keyboard / Piano','Used','Ragama,  Gampaha','https://ikman.lk/en/ad/piano-nevil-mendis-piano-for-sale-gampaha','Member','10/2/21 8:50');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('73','Guitar Pedal for sale','Posted on 12 Oct 5:58 pm, Wellampitiya, Colombo','Rs 5,500','Other Instrument','Used','Wellampitiya,  Colombo','https://ikman.lk/en/ad/guitar-pedal-for-sale-colombo-103','Member','10/12/21 17:58');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('74','Top speaker for sale','Posted on 12 Oct 5:57 pm, Gampaha City, Gampaha','Rs 32,000','Studio / Live Music Equipment','Used','Gampaha City,  Gampaha','https://ikman.lk/en/ad/top-speker-for-sale-gampaha-2','Member','10/12/21 17:57');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('75','Samson CL2 - Pencil Condenser Microphone Set for sale','Posted on 12 Oct 5:53 pm, Colombo 11, Colombo','Rs 54,900','Studio / Live Music Equipment','New','Colombo 11,  Colombo','https://ikman.lk/en/ad/samson-cl2-pencil-condenser-microphone-set-for-sale-colombo','Member','10/12/21 17:53');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('76','Samson Concert 288 All-In-One - Dual-Channel UHF Wireless System for sale','Posted on 12 Oct 5:42 pm, Colombo 11, Colombo','Rs 59,000','Studio / Live Music Equipment','New','Colombo 11,  Colombo','https://ikman.lk/en/ad/samson-concert-288-all-in-one-dual-channel-uhf-wireless-system-for-sale-colombo','Member','10/12/21 17:42');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('77','Piano ~Portable Touch Sensitive Digital Travel BX-20 ( Brand New ) for sale','Posted on 29 Sep 10:48 pm, Athurugiriya, Colombo','Rs 35,000','Keyboard / Piano','New','Athurugiriya,  Colombo','https://ikman.lk/en/ad/piano-portable-touch-sensitive-digital-travel-bx-20-brand-new-for-sale-colombo','Member','9/29/21 22:48');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('78','Electric Drum Set ( Brand New ) for sale','Posted on 05 Oct 8:14 pm, Athurugiriya, Colombo','Rs 18,500','Percussion / drums','New','Athurugiriya,  Colombo','https://ikman.lk/en/ad/electric-drum-set-brand-new-for-sale-colombo-1','Member','10/5/21 20:14');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('79','Keyboard for sale','Posted on 12 Oct 5:22 pm, Dehiwala, Colombo','Rs 12,000','Keyboard / Piano','Used','Dehiwala,  Colombo','https://ikman.lk/en/ad/for-sale-for-sale-colombo-18030','Member','10/12/21 17:22');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('80','BEHRINGER PO300 POWER OVERDRIVE for sale','Posted on 12 Oct 5:20 pm, Wadduwa, Kalutara','Rs 5,500','Studio / Live Music Equipment','Used','Wadduwa,  Kalutara','https://ikman.lk/en/ad/behringer-po300-power-overdrive-for-sale-kalutara','Member','10/12/21 17:20');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('81','Tik Tok Microphone for sale','Posted on 12 Oct 5:02 pm, Colombo 11, Colombo','Rs 1,499','Studio / Live Music Equipment','New','Colombo 11,  Colombo','https://ikman.lk/en/ad/tik-tok-microphone-for-sale-colombo-6','Member','10/12/21 17:02');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('82','''Fishman'' Eq with Tuner for sale','Posted on 12 Oct 5:02 pm, Kotte, Colombo','Rs 8,500','Studio / Live Music Equipment','New','Kotte,  Colombo','https://ikman.lk/en/ad/fishman-eq-with-tuner-for-sale-colombo-2','Member','10/12/21 17:02');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('83','ZOOM G2 guitar effect pedal (Credit card accepted) for sale','Posted on 12 Oct 4:59 pm, Wadduwa, Kalutara','Rs 12,500','Studio / Live Music Equipment','Used','Wadduwa,  Kalutara','https://ikman.lk/en/ad/zoom-g2-guitar-effect-pedal-credit-card-accepted-for-sale-kalutara','Member','10/12/21 16:59');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('84','Yamaha CX40 Classical Guitar for sale','Posted on 12 Oct 4:58 pm, Kandy City, Kandy','Rs 25,000','String Instrument / Amplifier','Used','Kandy City,  Kandy','https://ikman.lk/en/ad/yamaha-cx40-classical-guitar-for-sale-kandy','Member','10/12/21 16:58');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('85','Guitar Black Shine for sale','Posted on 12 Oct 4:55 pm, Colombo 8, Colombo','Rs 7,000','String Instrument / Amplifier','Used','Colombo 8,  Colombo','https://ikman.lk/en/ad/gitur-black-shine-for-sale-colombo','Member','10/12/21 16:55');
INSERT INTO instruments_for_sale_chicago(ID,Title,Sub_title,Price,Instrument_Type,Condition,Location,Post_URL,Seller_type,published_date) VALUES ('86','ROLAND SP20 for sale','Posted on 12 Oct 4:43 pm, Pallepola, Matale','Rs 140,000','Percussion / drums','Used','Pallepola,  Matale','https://ikman.lk/en/ad/roland-sp20-for-sale-matale','Member','10/12/21 16:43');
